
export const collegeData: string[] = [
  "A. P. Shah Institute of Technology",
  "Atharva College of Engineering",
  "Bharati Vidyapeeth College of Engineering, Navi Mumbai",
  "Datta Meghe College of Engineering, Airoli",
  "Don Bosco Institute of Technology, Kurla",
  "Dwarkadas J. Sanghvi College of Engineering, Vile Parle",
  "Elphinstone College",
  "Fr. Conceicao Rodrigues College of Engineering, Bandra",
  "Fr. Conceicao Rodrigues Institute of Technology, Vashi",
  "Indian Institute of Technology Bombay (IIT Bombay), Powai",
  "Institute of Chemical Technology (ICT), Matunga",
  "Jai Hind College",
  "K.J. Somaiya College of Engineering, Vidyavihar",
  "K.J. Somaiya Institute of Technology, Sion",
  "Kishinchand Chellaram College (KC College)",
  "Lokmanya Tilak College of Engineering, Kopar Khairane",
  "Mahavir Education Trust's Shah & Anchor Kutchhi Engineering College, Chembur",
  "Mahatma Education Society's Pillai College of Engineering, New Panvel",
  "Manjara Charitable Trust's Rajiv Gandhi Institute of Technology",
  "M.H. Saboo Siddik College of Engineering, Byculla",
  "Mithibai College of Arts",
  "Narsee Monjee College of Commerce and Economics",
  "Padmabhushan Vasantdada Patil Pratishthan's College of Engineering, Sion",
  "Ramnarain Ruia Autonomous College",
  "Rizvi College of Engineering, Bandra",
  "Sardar Patel College of Engineering",
  "Sardar Patel College of Engineering, Andheri",
  "Sardar Patel Institute of Technology, Andheri",
  "Shah and Anchor Kutchhi Engineering College",
  "Shivajirao S. Jondhale College of Engineering, Dombivali",
  "Sophia College for Women",
  "St. Francis Institute of Technology, Borivali",
  "St. Xavier's College, Mumbai",
  "Terna Engineering College, Nerul",
  "Thadomal Shahani Engineering College, Bandra",
  "Thakur College of Engineering and Technology, Kandivali",
  "The Kelkar Education Trust's V.G. Vaze College of Arts, Science and Commerce",
  "Veermata Jijabai Technological Institute (VJTI)",
  "Veermata Jijabai Technological Institute (VJTI), Matunga",
  "Vidyalankar Institute of Technology, Wadala",
  "Vidyavardhini College of Engineering and Technology, Vasai",
  "Vivekanand Education Society's Institute of Technology (VESIT), Chembur",
  "Watumull Institute of Engineering & Technology, Ulhasnagar",
  "Wilson College",
  "Xavier Institute of Engineering, Mahim"
];
